### ISSUE TITLE
A way to execute UI button operations from python ?

### ISSUE THREAD

**Issue by PavelSavkin** [mrachinskiy/booltron#13]
Hi, thank you so much for your awesome work !

After using it in UI, I've decided to automate some of the processes using python.

Could you provide an example how to execute let's say "Destructive Union" from a python script ?

I've already succeeded to automatically select objects to apply it, and the only left thins is to automatically press the above button.

Thanks.

**Comment by mrachinskiy** [comment]
Hi, enable `Edit` > `Preferences` > `Interface` > `Python Tooltips` option, then hover over any button in the UI and it will show the name of the operator to call.

For union it will be: `bpy.ops.object.booltron_destructive_union()`.

If you use Python Console editor and type `bpy.ops.object.booltron_destructive_union(` without closing bracket, then press `Tab` – it will autocomplete, showing various operator options.

**Comment by PavelSavkin** [comment]
Hi thanks ! I've tried that, resulting in the following error.
The wired thing is, that when I hit the button, it works, though when I run the script, I get this error.
(Objects are all correctly selected)

Do you have ideas how to resolve this ?

```
bpy.ops.object.booltron_destructive_union(solver='FAST', use_self=False, threshold=1e-06, use_pos_offset=False, pos_offset=0.005, merge_distance=0.0002, cleanup=False, triangulate=False, display_secondary='WIRE', display_combined='BOUNDS', keep_objects=False, first_run=True)
Error: Python: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\__init__.py", line 79, in execute
    return destructive_func.execute(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 31, in wrapper
    result = func(*args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 94, in execute
    if self.is_overlap:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_types.py", line 721, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'OBJECT_OT_destructive_union' object has no attribute 'is_overlap'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132


Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\__init__.py", line 79, in execute
    return destructive_func.execute(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 31, in wrapper
    result = func(*args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 94, in execute
    if self.is_overlap:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_types.py", line 721, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'OBJECT_OT_destructive_union' object has no attribute 'is_overlap'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132
```

**Comment by PavelSavkin** [comment]
Hi thanks ! I've tried that, resulting in the following error.
The wired thing is, that when I hit the button, it works, though when I run the script, I get this error.
(Objects are all correctly selected)

Do you have ideas how to resolve this ?
```
bpy.ops.object.booltron_destructive_union(solver='FAST', use_self=False, threshold=1e-06, use_pos_offset=False, pos_offset=0.005, merge_distance=0.0002, cleanup=False, triangulate=False, display_secondary='WIRE', display_combined='BOUNDS', keep_objects=False, first_run=True)
Error: Python: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\__init__.py", line 79, in execute
    return destructive_func.execute(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 31, in wrapper
    result = func(*args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 94, in execute
    if self.is_overlap:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_types.py", line 721, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'OBJECT_OT_destructive_union' object has no attribute 'is_overlap'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132


Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\__init__.py", line 79, in execute
    return destructive_func.execute(self, context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 31, in wrapper
    result = func(*args)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\booltron\ops_destructive\destructive_func.py", line 94, in execute
    if self.is_overlap:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy_types.py", line 721, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'OBJECT_OT_destructive_union' object has no attribute 'is_overlap'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132
```

**Comment by mrachinskiy** [comment]
You have to pass `INVOKE_DEFAULT` as first argument, it is explained in [documentation](https://docs.blender.org/api/master/bpy.types.Operator.html?highlight=%27invoke_default%27#invoke-function).

**Comment by PavelSavkin** [comment]
Yes it worked perfectly ! Thank you & sorry for missing those parts.

I really appreciate project ! thank you very much :)
